import {
  GamersImage,
  landify,
  covid,
  weather,
  calculator,
  todo,
  scores,
  recipe,
} from "../../assets";

export const Projects = [
  {
    avatar: "C",
    title: "Covid Tracker",
    imgSrc: covid,
    description: "Covid-19 cases in countries around the world.",
    codeUrl: "https://github.com/Mezebu/corona-tracker",
    pageUrl: "https://corona-tracker-ab94b.web.app/",
  },
  {
    avatar: "W",
    title: "Weather App",
    imgSrc: weather,
    description: "A weather web-app that collects weather information .",
    pageUrl: "https://weather-app-16dfa.web.app/",
    codeUrl: "https://github.com/Mezebu/weather-app",
  },
  {
    avatar: "R",
    title: "Recipe App",
    imgSrc: recipe,
    description: "The app grabs recipes from an external API",
    pageUrl: "https://recipe-app-46d04.web.app/",
    codeUrl: "https://github.com/Mezebu/recipe-app",
  },
  {
    avatar: "S",
    title: "Score Card",
    imgSrc: scores,
    description: "List of premier league games and scores.",
    pageUrl: "https://score-card-app.web.app/",
    codeUrl: "https://github.com/Mezebu/score-card-app",
  },
  {
    avatar: "G",
    title: "Gamers",
    imgSrc: GamersImage,
    description: "A web app that handles sign in and registration sessions.",
    codeUrl: "https://github.com/Mezebu/gamers",
    pageUrl: "https://gamers-fb7da.firebaseapp.com/",
  },
  {
    avatar: "C",
    title: "Calculator",
    imgSrc: calculator,
    description: "A simple javaScript calculator ",
    pageUrl: "https://mezebu.github.io/calculator/",
    codeUrl: "https://github.com/Mezebu/calculator",
  },
  {
    avatar: "T",
    title: "Todo-List",
    imgSrc: todo,
    description: "Displays, adds, removes and marks tasks as complete.",
    pageUrl: "https://todo-list-b03b4.web.app/",
    codeUrl: "https://github.com/Mezebu/todo-list",
  },
  {
    avatar: "L",
    title: "Landify",
    imgSrc: landify,
    description: "Landing page  built using react ",
    pageUrl: "https://landify-1e603.web.app/",
    codeUrl: "https://github.com/Mezebu/landify",
  },
];
